### ISSUE TITLE
v0.13 from opam has missing dune metadata

### ISSUE THREAD

**Issue by anuragsoni** [janestreet/async_websocket#1]
The dune file for the version published on opam doesn't define a `public_name`. 

```lisp
(library (name websocket)
 (libraries async core_kernel.binary_packing cryptokit)
 (preprocess (pps ppx_jane)))
```

The opam file also seems to be missing some dependencies (it doesn't list cryptokit and async as a dependency)
Running opam install works, but the library isn't usable.

This commit: https://github.com/janestreet/async_websocket/commit/a37f4c1f084e5c2273c50792ac8069e018d858da adds the metadata to the opam/dune files. I can confirm that i've tried pinning to the version in the repository and I can then use the library under utop and as a dependency via dune.

**Comment by xclerc** [comment]
Should be fixed by https://github.com/ocaml/opam-repository/pull/15633; feel free to
reopen the issue if it is not the case.

**Comment by anuragsoni** [comment]
Thank you! I can confirm that the new version published on opam works fine.

**Comment by xclerc** [comment]
Great; thanks for both the report and the confirmation.
